import assert from 'node:assert/strict';
import fs from 'node:fs';
const py=fs.readFileSync('backend/scripts/kronos_stage_b_diagnostic.py','utf8');
const live=fs.readFileSync('scripts/kronosStageBDiagnosticLive.mjs','utf8');
const routes=fs.readFileSync('server/researchValidationRoutes.ts','utf8');
assert.match(py,/KRONOS_STAGE_B_DIAGNOSTIC_V1_RESULT/);
assert.match(py,/PATHS=20/);
assert.match(py,/CHUNK=3/);
assert.match(py,/CONTEXT=512/);
assert.match(py,/HORIZON=60/);
assert.match(py,/2018,2026/);
assert.match(py,/2025 and m>9/);
assert.match(py,/predict_batch/);
assert.match(py,/sample_count=1/);
assert.match(py,/progress\.json/);
assert.match(py,/meanCrossSectionalRankIc/);
assert.match(py,/momentumMeanCrossSectionalRankIc/);
assert.match(py,/absoluteDirectionBrier/);
assert.match(py,/pretrainingCutoffKnown.*False/s);
assert.match(py,/historicalPromotionAllowed.*False/s);
assert.match(py,/productionDefault.*LEGACY/s);
assert.doesNotMatch(py,/productionAuthority.*True/s);
assert.match(live,/7200000/);
assert.match(live,/KRONOS_STAGE_B_RUNTIME_NOT_READY_RUN_STAGE_A/);
const a=routes.indexOf("id: 'kronos-stage-b-diagnostic-v1'");
assert.ok(a>=0);
const b=routes.indexOf("\n  },",a)+5;
const block=routes.slice(a,b);
assert.match(block,/visibility: 'CURRENT'/);
assert.match(block,/kronosStageBDiagnosticV1Seal\.unit\.mjs/);
assert.match(block,/kronosStageBDiagnosticV1\.unit\.mjs/);
assert.match(block,/kronosStageBDiagnosticV1Contract\.unit\.mjs/);
assert.match(block,/kronosStageALive\.mjs/);
assert.match(block,/kronosStageBDiagnosticLive\.mjs/);
console.log('kronosStageBDiagnosticV1Contract.unit: PASS');
