import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';

const routes = fs.readFileSync(path.resolve(process.cwd(), 'server/researchValidationRoutes.ts'), 'utf8');
const mount = fs.readFileSync(path.resolve(process.cwd(), 'server/alertAutomationRoutes.ts'), 'utf8');
const ui = fs.readFileSync(path.resolve(process.cwd(), 'src/components/ResearchValidationCenter.tsx'), 'utf8');
const main = fs.readFileSync(path.resolve(process.cwd(), 'src/decisionMain.tsx'), 'utf8');

assert.match(routes, /'sector-52w-high-leadership-v1'/);
assert.match(routes, /SECTOR_52W_HIGH_LEADERSHIP_V1_RESULT/);
assert.match(routes, /52W V1 · FAIL_DIAGNOSTIC · cerrado/);
assert.match(routes, /id: 'pead-earnings-source-audit-v1'/);
const peadStart = routes.indexOf("id: 'pead-earnings-source-audit-v1'");
const peadEnd = routes.indexOf("archivedJob(", peadStart);
const peadBlock = routes.slice(peadStart, peadEnd > peadStart ? peadEnd : undefined);
assert.match(peadBlock, /visibility: 'ARCHIVED'/);
assert.match(routes, /id: 'pead-analyst-surprise-v1'/);
const peadSignalStart = routes.indexOf("id: 'pead-analyst-surprise-v1'");
const peadSignalEnd = routes.indexOf("archivedJob(", peadSignalStart);
const peadSignalBlock = routes.slice(peadSignalStart, peadSignalEnd > peadSignalStart ? peadSignalEnd : undefined);
assert.match(peadSignalBlock, /visibility: 'PARKED'/);
assert.match(peadSignalBlock, /tests\/peadSignalDiagnosticV1Seal\.unit\.mjs/);
assert.match(peadSignalBlock, /tests\/peadSignalDiagnosticV1\.unit\.mjs/);
assert.match(peadSignalBlock, /scripts\/peadSignalDiagnosticV1\.mjs/);
assert.match(peadSignalBlock, /Yahoo REAL · diagnóstico PEAD 60 sesiones/);
const currentVisibilityCount = (routes.match(/visibility: 'CURRENT'/g) ?? []).length;
assert.equal(currentVisibilityCount, 1, 'Exactly one research line should be visible as CURRENT');
const parkedVisibilityCount = (routes.match(/visibility: 'PARKED'/g) ?? []).length;
assert.ok(parkedVisibilityCount >= 3, 'Parallel research lines should remain parked, not visible');
assert.match(routes, /tests\/peadEarningsSourceAuditV1\.unit\.mjs/);
assert.match(routes, /tests\/peadEarningsSourceAuditV1\.integration\.mjs/);
assert.match(routes, /scripts\/peadEarningsSourceAuditV1\.mjs/);
assert.match(peadBlock, /Fuente estática pinneada · auditar causalidad PEAD/);
assert.doesNotMatch(peadBlock, /requiresEodhdApiKey: true/);
assert.doesNotMatch(peadBlock, /EODHD REAL/);
assert.match(routes, /'pead-yahoo-calendar-source-audit-r2'/);
assert.match(routes, /PEAD source R2 · INCONCLUSIVE timing unavailable · cerrado/);
assert.match(routes, /id: 'pead-yahoo-calendar-source-audit-r3'/);
const peadR3Start = routes.indexOf("id: 'pead-yahoo-calendar-source-audit-r3'");
const peadR3End = routes.indexOf("id: 'pead-analyst-surprise-v1'", peadR3Start);
const peadR3Block = routes.slice(peadR3Start, peadR3End > peadR3Start ? peadR3End : undefined);
assert.match(peadR3Block, /visibility: 'PARKED'/);
assert.match(peadR3Block, /tests\/peadYahooCalendarSourceAuditR3Seal\.unit\.mjs/);
assert.match(peadR3Block, /tests\/peadYahooCalendarSourceAuditR3\.unit\.mjs/);
assert.match(peadR3Block, /tests\/peadYahooCalendarSourceAuditR2\.integration\.mjs/);
assert.match(peadR3Block, /scripts\/peadYahooCalendarSourceAuditR3\.mjs/);
assert.match(peadR3Block, /Yahoo REAL · auditar PEAD R3 next-session/);
assert.doesNotMatch(peadR3Block, /requiresEodhdApiKey: true/);
assert.match(peadSignalBlock, /tests\/peadSignalSourceR3Readiness\.unit\.mjs/);
assert.match(routes, /id: 'timesfm-stage-a-smoke-v1'/);
const timesfmStart = routes.indexOf("id: 'timesfm-stage-a-smoke-v1'");
const timesfmEnd = routes.indexOf("id: 'pead-yahoo-calendar-source-audit-r3'", timesfmStart);
const timesfmBlock = routes.slice(timesfmStart, timesfmEnd > timesfmStart ? timesfmEnd : undefined);
assert.match(timesfmBlock, /visibility: 'CURRENT'/);
assert.match(timesfmBlock, /tests\/timesfmStageAContract\.unit\.mjs/);
assert.match(timesfmBlock, /scripts\/timesfmStageABootstrap\.mjs/);
assert.match(timesfmBlock, /TIMESFM_STAGE_A_SMOKE_RESULT/);
assert.match(routes, /state\.result = extractJsonAfterMarker\(stepRun\.output, job\.marker\)/);
assert.match(routes, /exitCode: state\.exitCode/);
assert.match(routes, /error: state\.error/);
assert.doesNotMatch(routes, /state\.result = extractJsonAfterMarker\(state\.output, job\.marker\);\s*state\.status = 'FAILED'/);
assert.match(routes, /id: 'fundamental-quality-valuation-broad-pit-v1'/);
assert.match(routes, /scripts\/fundamentalQualityValuationBroadPitV1Live\.ts/);
assert.match(routes, /SEC_EDGAR_USER_AGENT_REQUIRED/);
assert.match(routes, /id: 'phase6-forward-risk-context-stage-a-r2-readiness'/);
assert.match(routes, /scripts\/phase6ForwardRiskContextStageAR2CollectorLive\.ts/);
assert.match(routes, /id: 'quality-allocation-dynamic-future-forward-v1'/);
assert.match(routes, /scripts\/qualityAllocationDynamicFutureForwardV1CheckpointLive\.ts/);
assert.match(routes, /'phase9-end-to-end-preclose-v1'/);
assert.match(routes, /Fase 9 · pre-cierre técnico V1 PASS · cerrado/);

assert.match(routes, /aiTokensUsed: false/);
assert.match(routes, /LOCAL_APP_BACKEND/);
assert.doesNotMatch(routes, /GEMINI|@google\/genai|github actions/i);

assert.match(mount, /research-validation/);
assert.match(ui, /Validación de investigación/);
assert.match(ui, /Ejecutar smoke TimesFM 3\.0/);
assert.match(ui, /Ejecutar audit Yahoo REAL PEAD R3/);
assert.match(ui, /Ejecutar diagnóstico 52W · rev\. técnica 3/);
assert.match(ui, /SECTOR_52W_HIGH_LEADERSHIP_V1/);
assert.match(ui, /Todo se ejecuta en el backend local, sin IA ni GitHub Actions/);
assert.match(ui, /\/api\/eodhd\/status/);
assert.match(ui, /\/api\/alpha-vantage\/status/);
assert.match(ui, /SEC EDGAR PIT/);
assert.match(ui, /FALTA USER-AGENT/);
assert.match(ui, /result\.json/);

assert.match(main, /ResearchValidationCenter/);
assert.match(main, /InteractiveInvestmentDecisionCenter/);
assert.doesNotMatch(main, /ForwardRiskResearchPanel/);

console.log('researchValidationRuntime.unit: PASS');
