import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
const root=process.cwd();
const read=p=>fs.readFileSync(path.resolve(root,p),'utf8');
const collector=read('scripts/timesfmStageBProspectiveCollectorLive.mjs');
const protocol=read('scripts/timesfmStageBProspectiveProtocol.mjs');
const store=read('scripts/timesfmStageBProspectiveStateStore.mjs');

assert.match(protocol,/noHistoricalCatchUp: true/);
assert.match(protocol,/noRetroactiveForecastAfterFirstCommonSessionPassed: true/);
assert.match(protocol,/futureOutcomeAccess: false/);
assert.match(protocol,/minimumMaturedAnchors: STAGE_B\.prospectiveConfirmation\.minimumMaturedAnchors/);
assert.match(protocol,/productionDefault: 'LEGACY'/);
assert.match(protocol,/productionAuthority: false/);
assert.match(protocol,/version: 'TIMESFM_DIRECT_SELECTOR_V1'/);
assert.match(protocol,/DIRECT_ASSET_SELECTOR_SHADOW/);
assert.match(protocol,/8_STAGE_B_ASSETS_PLUS_EUNL_CORE/);
assert.match(protocol,/LOWEST_MEAN_ORDINAL_RANK_20_60/);
assert.match(protocol,/100_PERCENT_EXECUTABLE_SHADOW_EQUITY_TO_SELECTED_ASSET/);
assert.match(protocol,/TIMESFM_MULTIVARIATE_CONTEXT_V1/);
assert.match(protocol,/collectBothFrozenArms: true/);
assert.match(protocol,/FULL_PANEL_TARGETS_ONLY/);
assert.match(protocol,/FULL_PANEL_PLUS_CAUSAL_COVARIATES/);
assert.match(protocol,/pastOnlyCovariates: MV\.covariates\.totalPastOnly/);
assert.match(protocol,/noRetuneAfterCollectionOpens: true/);

assert.match(collector,/MISSED_WEEK_NO_RETROACTIVE_FORECAST/);
assert.match(collector,/berlin\.date <= M\.startAfter/);
assert.match(collector,/payloadFingerprintSha256/);
assert.match(collector,/outcomesOpened:false/);
assert.match(collector,/economicShadowPolicyVersion:M\.economicShadow\.version/);
assert.match(collector,/selectDirectTimesFmWinner/);
assert.match(collector,/directShadow/);
assert.match(collector,/selectedAssetId/);
assert.match(collector,/selectedIsStructuralCore/);
assert.match(collector,/callTimesFmStageB\(payload\)/);
assert.match(collector,/callTimesFmMultivariateContextV1\(mvPayload\)/);
assert.match(collector,/buildCausalMultivariateContext\(series,informationDate\)/);
assert.match(collector,/multivariateSignalShadow/);
assert.match(collector,/targetsOnly:mvAnchor\.targetsOnly/);
assert.match(collector,/withCausalCovariates:mvAnchor\.withCausalCovariates/);
assert.match(collector,/outcomesOpened:false/);
assert.match(collector,/saveTimesFmProspectiveDurableState/);
assert.ok(collector.indexOf('const remote=await callTimesFmStageB(payload);') < collector.indexOf('state=appendTimesFmProspectiveAnchor'));
assert.ok(collector.indexOf('const mvRemote=await callTimesFmMultivariateContextV1(mvPayload);') < collector.indexOf('state=appendTimesFmProspectiveAnchor'));
assert.doesNotMatch(collector,/actualReturn|futureReturn|realizedReturn|realisedReturn/);
assert.doesNotMatch(collector,/evaluateStageB|StageBEvaluator/);

assert.match(store,/DEFAULT_BRANCH = 'replay-results'/);
assert.match(store,/GITHUB_REPLAY_SYNC_TOKEN/);
assert.match(store,/validation-runs\/timesfm-stage-b-prospective-confirmation-v1-state\.json/);
assert.match(store,/verifyTimesFmProspectiveState/);

console.log('timesfmStageBProspectiveContract.unit: PASS');
