import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';

const read = p => fs.readFileSync(path.resolve(process.cwd(), p), 'utf8');
const readme = read('runner/timesfm/hf-space/README.md');
const app = read('runner/timesfm/hf-space/app.py');
const client = read('scripts/timesfmStageARemoteClient.mjs');
const routes = read('server/researchValidationRoutes.ts');
const remote = read('server/timesfmRemoteRunner.ts');

assert.match(readme, /sdk: gradio/);
assert.match(readme, /python_version: 3\.12\.12/);
assert.match(app, /importlib\.util\.find_spec\("timesfm3"\)/);
assert.match(app, /"timesfm==3\.0\.2"/);
assert.match(app, /"numpy>=1\.26\.4,<3\.0\.0"/);
assert.match(app, /subprocess\.check_call/);
assert.doesNotMatch(app, /pip.*install.*torch/);
assert.match(app, /import spaces/);
assert.match(app, /@spaces\.GPU\(duration=GPU_DURATION_SECONDS\)/);
assert.match(app, /GPU_DURATION_SECONDS = 110/);
assert.match(app, /device="cuda"/);
assert.match(app, /google\/timesfm-3\.0-pytorch/);
assert.match(app, /24701cec1b1ea47232c0766e888855c9976ef62b/);
assert.match(app, /a7592b0a8432baee54483254e5647856911ce69e09d09a9bb65904b2d98f17da/);
assert.match(app, /full_with_future\[:, :information_cutoff\]/);
assert.match(app, /api_name="status"/);
assert.match(app, /api_name="run_stage_a"/);
assert.match(app, /zeroCostInfrastructure": True/);
assert.doesNotMatch(app, /Yahoo|EODHD|SEC_EDGAR|PortfolioDecisionEngine|PortfolioCandidateGate/);
assert.match(client, /\/gradio_api\/call\//);
assert.match(client, /TIMESFM_ZEROGPU/);
assert.doesNotMatch(client, /TIMESFM_RUNNER_TOKEN/);
assert.match(remote, /DEFAULT_TIMESFM_ZERO_GPU_URL/);
assert.match(remote, /fetchTimesFmRemoteState/);
assert.match(remote, /reconcileTimesFmState/);
assert.match(remote, /runTimesFmRemoteStageA/);
assert.match(remote, /\/gradio_api\/call\//);
assert.doesNotMatch(remote, /TIMESFM_RUNNER_TOKEN/);
assert.match(routes, /requiresTimesFmRunner: true/);
assert.match(routes, /scripts\/timesfmStageARemoteClient\.mjs/);
console.log('timesfmRemoteRunnerContract.unit: PASS');
