import assert from 'node:assert/strict';
import { TIMESFM_MULTIVARIATE_CONTEXT_V1 as P, quarterEndCalendarDates, validateTimesFmMultivariateContextProtocol } from '../scripts/timesfmMultivariateContextV1Protocol.mjs';

assert.equal(validateTimesFmMultivariateContextProtocol(),true);
assert.equal(P.version,'TIMESFM_MULTIVARIATE_CONTEXT_V1');
assert.equal(P.model.packageVersion,'3.0.2');
assert.equal(P.model.checkpoint,'google/timesfm-3.0-pytorch');
assert.equal(P.targets.length,9);
assert.equal(new Set(P.targets.map(x=>x.assetId)).size,9);
assert.equal(P.contextLength,512);
assert.equal(P.forecastHorizon,60);
assert.deepEqual(P.primaryHorizons,[20,60]);
assert.equal(P.arms.fullPanelTargetsOnly.targetVariates,9);
assert.equal(P.arms.fullPanelTargetsOnly.pastOnlyCovariates,0);
assert.equal(P.arms.fullPanelCausalCovariates.targetVariates,9);
assert.equal(P.arms.fullPanelCausalCovariates.pastOnlyCovariates,23);
assert.equal(P.arms.fullPanelCausalCovariates.targetVariates+P.arms.fullPanelCausalCovariates.pastOnlyCovariates,32);
assert.equal(P.covariates.perTarget.length,2);
assert.equal(P.covariates.shared.length,5);
assert.equal(P.covariates.totalPastOnly,23);
assert.deepEqual(P.covariates.futureKnownCovariates,[]);
assert.equal(P.diagnostic.expectedAnchors,31);
assert.equal(quarterEndCalendarDates().length,31);
assert.equal(P.interpretation.noPromotionFromHistorical,true);
assert.equal(P.interpretation.noEconomicPolicyInThisStudy,true);
assert.equal(P.prospective.freezeBothArmsBeforeFirstAnchor,true);
assert.equal(P.prospective.firstEligibleIsoWeek,'2026-W42');
assert.equal(P.prospective.outcomesOpened,false);
assert.equal(P.productionDefault,'LEGACY');
assert.equal(P.productionAuthority,false);
console.log('timesfmMultivariateContextV1.unit: PASS');
