import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';

const root=process.cwd();
const protocol=fs.readFileSync(path.resolve(root,'scripts/timesfmMultivariateContextV1Protocol.mjs'),'utf8');
const diagnostic=fs.readFileSync(path.resolve(root,'scripts/timesfmMultivariateContextV1DiagnosticLive.mjs'),'utf8');
const client=fs.readFileSync(path.resolve(root,'scripts/timesfmMultivariateContextV1RemoteClient.mjs'),'utf8');
const endpoint=fs.readFileSync(path.resolve(root,'scripts/hfTimesFmMultivariateContextV1Endpoint.py'),'utf8');

assert.match(protocol,/maxVariates: 32/);
assert.match(protocol,/pastOnlyCovariates: 23/);
assert.match(protocol,/futureKnownCovariates: Object\.freeze\(\[\]\)/);
assert.match(protocol,/EVERY_VALUE_MUST_BE_DERIVED_FROM_DATA_AT_OR_BEFORE_INFORMATION_DATE/);
assert.match(diagnostic,/targetContext:a\.targetContext,pastOnlyCovariates:a\.pastOnlyCovariates/);
assert.doesNotMatch(diagnostic,/pastFutureCovariates/);
assert.match(diagnostic,/const remote=await callTimesFmMultivariateContextV1\(payload\);const remoteByAnchor/);
assert.ok(diagnostic.indexOf('callTimesFmMultivariateContextV1(payload)') < diagnostic.indexOf("evaluateArm('TARGETS_ONLY'"),'Forecast must be obtained before outcomes are evaluated');
assert.doesNotMatch(diagnostic,/DynamicHistoricalReplay|PortfolioDecisionEngine|OpportunityAllocationPolicy/);
assert.match(client,/multivariate_context_predict/);
assert.match(client,/TIMESFM_MULTIVARIATE_RUNNER_ENDPOINT_REQUIRED/);
assert.match(endpoint,/TimesFM3Forecaster/);
assert.match(endpoint,/context=target_context/);
assert.match(endpoint,/past_only_covariates=past_cov/);
assert.doesNotMatch(endpoint,/past_future_covariates=/);
assert.match(endpoint,/use_znorm=True/);
assert.match(endpoint,/return_quantiles=True/);
assert.match(endpoint,/_as_2d\(anchor\.get\("targetContext"\), 9, context_len/);
assert.match(endpoint,/_as_2d\(anchor\.get\("pastOnlyCovariates"\), covariate_count, context_len/);
assert.match(endpoint,/@spaces\.GPU/);
console.log('timesfmMultivariateContextV1Contract.unit: PASS');
