import {
  PHASE5_ASSETS_PER_COHORT,
  PHASE5_COHORT_COUNT,
  PHASE5_CURRENT_DISCOVERY_HISTORICAL,
  PHASE5_FREQUENCY,
  PHASE5_HORIZON_YEARS,
  PHASE5_INITIAL_CAPITAL_EUR,
  PHASE5_MATERIALITY_CAPITAL_PCT,
  PHASE5_MEDIAN_MAX_DRAWDOWN_WORSENING_LIMIT_PP,
  PHASE5_MINIMUM_CAUSAL_BARS,
  PHASE5_PASS_MIN_POSITIVE_COHORTS,
  PHASE5_REACH_MIN_COHORTS,
  PHASE5_REACH_MIN_EXECUTED_REDUCTIONS,
  PHASE5_RISK_PROFILE,
  PHASE5_SINGLE_COHORT_MAX_DRAWDOWN_WORSENING_PP,
  PHASE5_SINGLE_COHORT_MAX_LOSS_PCT_INITIAL,
  PHASE5_TARGET_ASSETS
} from './phase5WinnerProtectionV2SampleProtocol';
import {
  PHASE5_SEALED_COHORTS,
  PHASE5_SEALED_SAMPLE
} from './phase5WinnerProtectionV2SealedSample';

export const PHASE5_CONFIRMATION_VERSION = 'PHASE5_WINNER_PROTECTION_V2_CONFIRMATION_V1' as const;
export const PHASE5_CONFIRMATION_PREFLIGHT_MARKER = 'PHASE5_WINNER_PROTECTION_V2_CONFIRMATION_PREFLIGHT_RESULT' as const;
export const PHASE5_CONFIRMATION_RESULT_MARKER = 'PHASE5_WINNER_PROTECTION_V2_CONFIRMATION_RESULT' as const;
export const PHASE5_CONFIRMATION_JOB_ID = 'phase5-winner-protection-v2-confirmation' as const;
export const PHASE5_CONFIRMATION_SEAL_PATH = 'validation-runs/preregistration/phase5-winner-protection-v2-confirmation-seal.json' as const;
export const PHASE5_CONFIRMATION_DATA_START_DATE = '2004-01-02';

/**
 * Original confirmation boundary: 2005-01-03.
 * The first coverage-only preflight opened no baseline/candidate economics and
 * showed 17/18 assets eligible. REP.MC had 251 causal bars versus the frozen
 * minimum of 252; provider/currency/integrity/end coverage were otherwise valid.
 *
 * Because the economic holdout remained unopened, only the temporal scoring
 * boundary is refrozen to 2005-01-10. The one-week buffer is based exclusively
 * on observed provider coverage, preserves the full 2004 non-scored warm-up,
 * keeps all 18 identities/cohorts and every economic threshold unchanged, and
 * avoids iterative one-session boundary chasing.
 */
export const PHASE5_CONFIRMATION_REPLAY_START_DATE = '2005-01-10';
export const PHASE5_CONFIRMATION_END_DATE = '2007-12-31';
export const PHASE5_CONFIRMATION_SAMPLE_STATE = 'PREOPEN_COVERAGE_ONLY_CONFIRMATION_NOT_OPENED' as const;
export const PHASE5_CONFIRMATION_SELECTION_RULE = 'SAME_18_SEALED_IDENTITIES_AND_COHORTS_TEMPORAL_REPLICATION_NO_RESELECTION' as const;

// Confirmation deliberately inherits the exact first-blind economics and gates.
// These aliases make drift visible instead of copying independent parameters.
export const PHASE5_CONFIRMATION_MINIMUM_CAUSAL_BARS = PHASE5_MINIMUM_CAUSAL_BARS;
export const PHASE5_CONFIRMATION_COHORT_COUNT = PHASE5_COHORT_COUNT;
export const PHASE5_CONFIRMATION_ASSETS_PER_COHORT = PHASE5_ASSETS_PER_COHORT;
export const PHASE5_CONFIRMATION_TARGET_ASSETS = PHASE5_TARGET_ASSETS;
export const PHASE5_CONFIRMATION_INITIAL_CAPITAL_EUR = PHASE5_INITIAL_CAPITAL_EUR;
export const PHASE5_CONFIRMATION_FREQUENCY = PHASE5_FREQUENCY;
export const PHASE5_CONFIRMATION_RISK_PROFILE = PHASE5_RISK_PROFILE;
export const PHASE5_CONFIRMATION_HORIZON_YEARS = PHASE5_HORIZON_YEARS;
export const PHASE5_CONFIRMATION_CURRENT_DISCOVERY_HISTORICAL = PHASE5_CURRENT_DISCOVERY_HISTORICAL;
export const PHASE5_CONFIRMATION_REACH_MIN_EXECUTED_REDUCTIONS = PHASE5_REACH_MIN_EXECUTED_REDUCTIONS;
export const PHASE5_CONFIRMATION_REACH_MIN_COHORTS = PHASE5_REACH_MIN_COHORTS;
export const PHASE5_CONFIRMATION_PASS_MIN_POSITIVE_COHORTS = PHASE5_PASS_MIN_POSITIVE_COHORTS;
export const PHASE5_CONFIRMATION_MATERIALITY_CAPITAL_PCT = PHASE5_MATERIALITY_CAPITAL_PCT;
export const PHASE5_CONFIRMATION_MEDIAN_MAX_DRAWDOWN_WORSENING_LIMIT_PP = PHASE5_MEDIAN_MAX_DRAWDOWN_WORSENING_LIMIT_PP;
export const PHASE5_CONFIRMATION_SINGLE_COHORT_MAX_LOSS_PCT_INITIAL = PHASE5_SINGLE_COHORT_MAX_LOSS_PCT_INITIAL;
export const PHASE5_CONFIRMATION_SINGLE_COHORT_MAX_DRAWDOWN_WORSENING_PP = PHASE5_SINGLE_COHORT_MAX_DRAWDOWN_WORSENING_PP;

// No asset re-selection is permitted after the first PASS. Confirmation tests
// temporal generalization of the exact same frozen cross-section and grouping.
export const PHASE5_CONFIRMATION_SAMPLE = PHASE5_SEALED_SAMPLE;
export const PHASE5_CONFIRMATION_COHORTS = PHASE5_SEALED_COHORTS;
